repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/autoflake
    rev: v1.5.3
    hooks:
    -   id: autoflake
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-json
        exclude: '^\.vscode/'
    -   id: check-yaml
    -   id: check-toml
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
    - id: prettier
      types_or: [javascript, html, css]
