"""type stubs for js functions"""

def append_register(reg: int, val: int) -> None: ...
def update_register(reg: int, val: int) -> None: ...
def append_memory(address: int, val: int) -> None: ...
def update_memory(address: int, val: int) -> None: ...
def append_instructions(cmd_json_str: str) -> None: ...
