def get_toy_svg_directives() -> dict[str, list]:
    return {
        # Paths to highlight
        "path-accu-pc-accu-is-zero": ["highlight", False],
        "path-accu-alu": ["highlight", False],
        "path-alu-junction": ["highlight", False],
        "path-junction-accu": ["highlight", False],
        "path-junction-ram": ["highlight", False],
        "path-opcode-control-unit": ["highlight", False],
        "path-instaddress-junction": ["highlight", False],
        "path-junction-pc": ["highlight", False],
        "path-junction-multiplexer": ["highlight", False],
        "path-pc-multiplexer": ["highlight", False],
        "path-multiplexer-ram": ["highlight", False],
        "path-ram-junction": ["highlight", False],
        "path-junction-alu": ["highlight", False],
        "path-junction-ir": ["highlight", False],
        # Texts to change
        "text-mnemonic": ["write", ""],
        "text-opcode": ["write", ""],
        "text-address": ["write", ""],
        "text-program-counter": ["write", ""],
        "text-ram-out": ["write", ""],
        "text-accu": ["write", ""],
        # Texts to change and hide
        "group-old-opcode-and-mnemonic": ["show", False],
        "group-old-pc": ["show", False],
        "group-old-accu": ["show", False],
        "group-alu-out": ["show", False],
        "text-old-opcode-and-mnemonic": ["write", ""],
        "text-old-pc": ["write", ""],
        "text-old-accu": ["write", ""],
        "text-alu-out": ["write", ""],
        # Control Unit arrows and texts to highlight
        "path-control-unit-write-ram": ["highlight", False],
        "text-write-ram": ["highlight", False],
        "path-control-unit-inc-pc": ["highlight", False],
        "text-inc-pc": ["highlight", False],
        "path-control-unit-set-pc": ["highlight", False],
        "text-set-pc": ["highlight", False],
        "path-control-unit-addr-ir": ["highlight", False],
        "text-addr-ir": ["highlight", False],
        "path-control-unit-set-ir": ["highlight", False],
        "text-set-ir": ["highlight", False],
        "path-control-unit-set-accu": ["highlight", False],
        "text-set-accu": ["highlight", False],
        "path-control-unit-alucin": ["highlight", False],
        "text-alucin": ["highlight", False],
        "path-control-unit-alumode": ["highlight", False],
        "text-alumode": ["highlight", False],
        "path-control-unit-alu3": ["highlight", False],
        "text-alu3": ["highlight", False],
        "path-control-unit-alu2": ["highlight", False],
        "text-alu2": ["highlight", False],
        "path-control-unit-alu1": ["highlight", False],
        "text-alu1": ["highlight", False],
        "path-control-unit-alu0": ["highlight", False],
        "text-alu0": ["highlight", False],
    }
